## Rol: Kustomization de orchestrare pentru infrastructura clusterului minirack
## Scop: Listează Kustomization-urile Flux (controllers + configs) și aplică un patch de path pentru `infrastructure`.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces.yaml
- infrastructure.yaml
- cert-manager.yaml
- cert-manager-configs.yaml
- secrets-configs.yaml
- metallb-configs.yaml
- monitoring.yaml
- keepalived.yaml
- k3s-configs.yaml
patches:
- target:
    kind: Kustomization
    name: infrastructure
  patch: |-
    - op: replace
      path: /spec/path
      value: ./infrastructure/controllers