## Rol: Kustomization Flux pentru secretele globale
## Scop: Sincronizează secretele globale (ex: MNEMONIC) în namespace-ul default. Include SOPS pentru decriptare.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-configs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/configs/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age

