{{- if .Values.registryCredentials.create -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: diod.adminui-tech-pull-token-{{ .Values.environmentType }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adminui.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "adminui.regcredData" . }}
{{- end }}
