# Kustomization base for the entangled-frontend application.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: entangled-frontend
commonLabels:
  app.kubernetes.io/part-of: entangled-frontend
resources:
- namespace.yaml
- config/configmap-entangled-frontend.yaml
- services/service-entangled-frontend-web.yaml
- workloads/deployment-entangled-frontend-web.yaml

