# ConfigMap patch for entangled-frontend dev environment to update GOMAESTRO_ENV.
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-entangled-frontend
  namespace: entangled-frontend
data:
  GOMAESTRO_ENV: "preprod"

