# ConfigMap patch for entangled-frontend dev environment to update GOMAESTRO_ENV.
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-entangled-frontend
  namespace: entangled-frontend
data:
  DELEGATION_SERVICE: "http://dev-service-delegation-service.delegation-service.svc.cluster.local:8082"
  GOMAESTRO_ENV: "preprod"

