# Deployment patch for entangled-frontend dev environment to update ConfigMap reference and add environment label.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-entangled-frontend-web
  namespace: entangled-frontend
spec:
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: container-entangled-frontend-web
          envFrom:
            - configMapRef:
                name: dev-configmap-entangled-frontend
            - secretRef:
                name: dev-secret-entangled-frontend
