# Kustomization overlay "dev" for the raffleize-frontend application.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: raffleize-frontend
namePrefix: dev-
resources:
  - ../base
  - networking/certificates/certificate-raffleize-frontend-dev-cardano-vip.yaml
  - networking/gateways/gateway-raffleize-frontend-dev-web.yaml
  - networking/routes/httproute-raffleize-frontend-dev-web-redirect.yaml
  - networking/routes/httproute-raffleize-frontend-dev-web.yaml
  - secrets/secret-raffleize-frontend.yaml

patchesStrategicMerge:
  - patches/configmap-raffleize-frontend.yaml
  - patches/deployment-raffleize-frontend-web.yaml
  - patches/service-raffleize-frontend-web.yaml
images:
  - name: mariusgeorgescu/raffleize-frontend
    newTag: dev

