# Deployment patch for bjjbackend interaction-api dev environment to add environment label.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bjjbackend-interaction-api
  namespace: bjj
spec:
  template:
    metadata:
      labels:
        environment: dev

