# Deployment patch for bjjbackend query-api dev environment to add environment label.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bjjbackend-query-api
  namespace: bjj
spec:
  template:
    metadata:
      labels:
        environment: dev

