{{- if .Values.registryCredentials.create -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: gitlab-delivery-management-tech-pull-token-{{ .Values.environmentType }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "delivery_management.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "delivery_management.regcredData" . }}
{{- end }}
