{{- if .Values.keycloak.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: comd-keycloak-client-secret
  labels:
    {{- include "delivery_management.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_CLIENT_SECRET: {{ .Values.keycloak.clientSecret | b64enc }}
{{- end }}
