apiVersion: v1
kind: Secret
metadata:
  name: {{ include "delivery_management.fullname" . }}-keystore-p12
  labels:
    {{- include "delivery_management.labels" . | nindent 4 }}
data:
  keystore-p12: {{ .Values.keyStoreP12}}