{{- if .Values.registryCredentials.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred-{{ template "delivery_management.fullname" . }}
  labels:
    {{- include "delivery_management.labels" . | nindent 4 }}
data:
  .dockerconfigjson: >-
    {{ template "delivery_management.regcredData" . }}
{{- end }}
