# Kustomization base for the raffleize-frontend application.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: raffleize-frontend
commonLabels:
  app.kubernetes.io/part-of: raffleize-frontend
resources:
- namespace.yaml
- config/configmap-raffleize-frontend.yaml
- services/service-raffleize-frontend-web.yaml
- workloads/deployment-raffleize-frontend-web.yaml

