# Kustomization overlay "prod" for the entangled-frontend application.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: entangled-frontend
namePrefix: prod-
resources:
  - ../base
  - networking/certificates/certificate-entangled-frontend-prod-cardano-vip.yaml
  - networking/gateways/gateway-entangled-frontend-prod-web.yaml
  - networking/routes/httproute-entangled-frontend-prod-web-redirect.yaml
  - networking/routes/httproute-entangled-frontend-prod-web.yaml
patchesStrategicMerge:
  - patches/configmap-entangled-frontend.yaml
  - patches/deployment-entangled-frontend-web.yaml
  - patches/service-entangled-frontend-web.yaml
images:
  - name: mariusgeorgescu/entangled-frontend
    newTag: prod
