{{- if .Values.registryCredentials.create -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: gitlab.order-capture-tech-pull-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order_capture.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "order_capture.regcredData" . }}
{{- end }}