{{- if or .Values.mongo.enabled .Values.mongo.host -}}
apiVersion: v1
kind: Secret
metadata:
  name: order-capture-mongo-secret-{{ .Values.environmentType }}
  labels:
    {{- include "order_capture.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_DB_PWD: {{ .Values.mongo.auth.rootPassword | b64enc }}
{{- end }}