apiVersion: v1
kind: Secret
metadata:
  name: product-catalog-mongo-secret
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_DB_PWD: {{ default "root" .Values.database.rootPassword | b64enc }}