{{- if or .Values.mongo.enabled .Values.mongo.host -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "order_inventory.fullname" . }}-spring
  labels:
    {{- include "order_inventory.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongo.auth.enabled }}
  # Use mongo_user credentials - the user created by bitnami MongoDB chart
  spring-db: {{ printf "{\"spring\": {\"data\": {\"mongodb\": { \"host\": \"%s\", \"port\": 27017, \"database\": \"order_inventory\", \"username\": \"mongo_user\", \"password\": \"discodevpassword\", \"authentication-database\": \"order_inventory\"}}}}"  (.Values.mongo.service.nameOverride) | b64enc }}
  {{- else }}
  spring-db: {{ printf "{\"spring\": {\"data\": {\"mongodb\": { \"host\": \"%s\", \"port\": 27017, \"database\": \"order_inventory\"}}}}"  (.Values.mongo.service.nameOverride) | b64enc }}
  {{- end }}
{{- end }}