{{- if or .Values.mongo.enabled .Values.mongo.host -}}
apiVersion: v1
kind: Secret
metadata:
  name: auth-userrole-mongo-secret
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_DB_PWD: {{ .Values.mongo.auth.rootPassword | b64enc }}
{{- end }}