{{- if .Values.registryCredentials.create -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: gitlab-orchestration-delivery-fallout-tech-pull-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orchestration_delivery_fallout.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "orchestration_delivery_fallout.regcredData" . }}
{{- end }}