apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestration_delivery_fallout.fullname" . }}-keystore-p12
  labels:
    {{- include "orchestration_delivery_fallout.labels" . | nindent 4 }}
data:
  keystore-p12: {{ .Values.keyStoreP12}}
