apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orchestration_delivery_fallout.fullname" . }}
  labels:
    {{- include "orchestration_delivery_fallout.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/orchestration-delivery-fallout.yml").AsConfig | nindent 2 }}
