{{- if or .Values.mongo.enabled .Values.mongo.host -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestration_delivery_fallout.fullname" . }}-spring
  labels:
    {{- include "orchestration_delivery_fallout.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongo.auth.enabled }}
  spring-db: {{ printf "{\"spring\": {\"data\": {\"mongodb\": { \"uri\": \"mongodb://%s:%s@%s:27017/orchestration_delivery_fallout?replicaSet=rs0&authSource=orchestration_delivery_fallout\", \"database\": \"orchestration_delivery_fallout\", \"host\": \"%s\", \"port\": 27017, \"authentication-database\": \"orchestration_delivery_fallout\", \"username\": \"%s\", \"password\": \"%s\"}}}}"  (.Values.mongo.auth.rootUser) (.Values.mongo.auth.rootPassword) (.Values.mongo.service.nameOverride) (.Values.mongo.service.nameOverride) (.Values.mongo.auth.rootUser) (.Values.mongo.auth.rootPassword) | b64enc }}
  {{- else }}
  spring-db: {{ printf "{\"spring\": {\"data\": {\"mongodb\": { \"uri\": \"mongodb://%s:27017/orchestration_delivery_fallout?replicaSet=rs0\", \"database\": \"orchestration_delivery_fallout\"}}}}" (.Values.mongo.service.nameOverride) | b64enc }}
  {{- end }}
{{- end }}
