{{- if .Values.registryCredentials.create -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: gitlab-orchestration-delivery-tech-pull-token-{{ .Values.environmentType }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orchestration_delivery.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "orchestration_delivery.regcredData" . }}
{{- end }}