{{- if .Values.keycloak.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: cood-keycloak-client-secret-{{ .Values.environmentType }}
  labels:
    {{- include "orchestration_delivery.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_CLIENT_SECRET: {{ .Values.keycloak.clientSecret | b64enc }}
{{- end }}