{{- if or .Values.mongo.enabled .Values.mongo.host -}}
apiVersion: v1
kind: Secret
metadata:
  name: orchestration-delivery-mongo-secret-{{ .Values.environmentType }}
  labels:
    {{- include "orchestration_delivery.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_DB_PWD: {{ .Values.mongo.auth.rootPassword | b64enc }}
{{- end }} 
