apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestration_delivery.fullname" . }}-keystore-p12
  labels:
    {{- include "orchestration_delivery.labels" . | nindent 4 }}
data:
  keystore-p12: {{ .Values.keyStoreP12}}