{{- if .Values.registryCredentials.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred-{{ template "orchestration_delivery.fullname" . }}
  labels:
    {{- include "orchestration_delivery.labels" . | nindent 4 }}
data:
  .dockerconfigjson: >-
    {{ template "orchestration_delivery.regcredData" . }}
{{- end }}