{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestration_delivery.serviceAccountName" . }}
  labels:
    {{- include "orchestration_delivery.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "orchestration_delivery.serviceAccountName" . }}-namespace-reader
  labels:
    {{- include "orchestration_delivery.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "orchestration_delivery.serviceAccountName" . }}-namespace-reader-binding
  labels:
    {{- include "orchestration_delivery.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "orchestration_delivery.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "orchestration_delivery.serviceAccountName" . }}-namespace-reader
  apiGroup: ""
{{- end }}