# Kustomization overlay "dev" pentru aplica»õia scavangerminephone
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scavangerminephone
namePrefix: dev-
resources:
  - ../base

