# Kustomization base pentru aplica»õia scavangerminephone
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scavangerminephone
commonLabels:
  app.kubernetes.io/part-of: scavangerminephone
resources:
- namespace.yaml
- secrets/secret-mnemonic.yaml
- services/service-scavangerminephone.yaml
- workloads/statefulset-scavangerminephone.yaml

