## Secret SOPS cu MNEMONIC global (disponibil Ã®n toate namespace-urile prin namespace default).
apiVersion: v1
kind: Secret
metadata:
    name: secret-mnemonic
    namespace: default
type: Opaque
stringData:
    MNEMONIC: ENC[AES256_GCM,data:P3VnFtuAS32NVRyzQlfZzwU+H5IV6Tfg2K/JnpOW0QFGINMln8ER503+8QKdRJIoLA6OOT0HoTYA0090fUiu+9wxQbFxMLiPI2FkQwqOnYCC/2+HA8o=,iv:26ejRQ6zAlmtFYxZ/juCls8OmysPQI8hXz3REnF1yzU=,tag:2G7e3bsCAcSXKS6LhSWltA==,type:str]
sops:
    age:
        - recipient: age13hn00phdudrnrvgqd0e9x8ndkk95jtnrqfp8n0g5d86cnhrj99csyc08c6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dkNIdTVtNkNyN0lQSGo0
            ajE4d3kwU2MzMXBIUWszTGxSVW9sMjh2QWdrCmsvUkZoWjhSRHY2Mmk3clFETWNj
            UDJvNml6NVloejVzQTBiYXY2cWI2TG8KLS0tIGZMaU1qU0ZTaXBCdjhoVm50ZXVk
            M1ZnUFZ1TTlucDdtVEcrdytpMG01SEkKXQaDaz6FCER+wa3uh7PQ7Esp3LNJiwdg
            rs3mubOT3l+G0YZUQ1Q290lZxrSq7IUPcOYhXgYUucrADqEAi74ZdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T20:03:30Z"
    mac: ENC[AES256_GCM,data:NX92SLAcQHEfWuAJyQnF9J9/QghCG8GnY8Aru03mhTW9gBZjz2dbbnb1R+9JYXbADMCasvSu3RaYXNuiyntF7TJ0Qrwg4PEARwoxjLnFRJ09LtZ6oMxXvbbJIrMVIdddNfBtTd+KXf3DjWVx51h3c9GQej5L7nY7TPsF2oIYDdM=,iv:sdbotOXEp8QZxrKmkeO4GrDJs6RhW1DEnMyL75Uu1cs=,tag:IDCPSs6gaZ9UeMTrRVwv1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
