apiVersion: v2
appVersion: 1.13.1
dependencies:
- alias: mongo
  condition: mongo.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami/
  tags:
  - spring-java-app-nosql-store
  version: 15.3.0
description: A Helm chart for [order management]/[product order inventory] service
keywords:
- discobole
- order-management
- order-inventory
name: order-inventory
type: application
version: 1.13.1
