apiVersion: v2
appVersion: 1.5.0
dependencies:
- alias: mongo
  condition: mongo.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami/
  version: 15.3.0
description: A Helm chart for product catalog  service
home: https://gitlab.ow2.org/discobole
icon: https://gitlab.ow2.org/uploads/-/system/group/avatar/5972/discobole_50_black.png?width=48
keywords:
- orange
- discobole
- catalog-product-catalog
- product-catalog
name: catalog-product-catalog
sources:
- https://gitlab.ow2.org/discobole/disco-oda-components/disco-catalog/catalog-product-catalog
type: application
version: 1.5.0
