# SPDX-FileCopyrightText: 2025 Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT License,
# the text of which is available at https://opensource.org/license/mit
# or see the "LICENSE.txt" file for more details.
#
# Authors: See CONTRIBUTORS.txt

# Default values for lifecycle-management.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Application replica count
replicaCount: 1

# Keystore in P12 format, base64 encoded
keyStoreP12: ""

# -- Enable or disable application daily shutdown
dailyshutdown: enabled

# Docker image parameters
image:
  #  -- docker image repository
  repository: "europe-central2-docker.pkg.dev/ino-it-s-disco-dev/disco-gcp/disco/catalog-product-catalog"
  # -- image pull policy
  pullPolicy: Always
  # - overrides the image tag whose default is the chart appVersion.
  tag: "1.5.0"

# -- Specify pulling image secrets if your image repository requires it
imagePullSecrets: []

# -- Override default fully qualified app name and chart name
nameOverride: ""

# -- Override fully qualified app name
fullnameOverride: ""

#  MongoDB configuration
database:
  enabled: true
  rootPassword: ""
  rootUser: mongo_user

#  External services configuration
services:
  # -- hostname and port of mongo
  mongodb: catalog-mongo
  # -- Mongo database name
  dbname: catalog
  # dbport: "27017"
  # -- hostname and port of kafka
  kafka: kafka:9092
  # -- hostname and port of keycloak
  keycloak: keycloak:80
  # -- Keycloak realm
  keycloakrealm: SpringBootKeycloak
  # -- catalog-ui service
  catalogui: catalog-ui:80
  # -- dependent microservice
  productcatalog: catalog-product-catalog:8080
  # -- dependent microservice  
  specification: catalog-product-specification:8080
  # -- dependent microservice  
  offering: catalog-product-offering:8080
  # -- dependent microservice  
  offeringprice: catalog-product-offering-price:8080
  # -- dependent microservice  
  category: catalog-product-category:8080
  # -- dependent microservice  
  lifecycle: catalog-product-lifecycle-management:8080
  # -- dependent microservice  
  userroleretrieve: auth-userrole:8080
  # -- dependent microservice  
  mockservice: mock-server:80
  # -- dependent microservice  
  gateway: disco-gateway:8080
  # -- dependent microservice  
  keycloakroute: keycloak

keycloak:
  enabled: false
  clientSecret: ""
  issuerURI: ""

serviceAccount:
  # -- specifies whether a service account should be created
  create: false
  # -- annotations to add to the service account
  annotations: {}
  # If not set and create is true, a name is generated using the fullname template
  # -- name of the service account
  name: ""

# enable monitoring and supervision of pods
podAnnotations: {}
  #prometheus.io/port: '9000'
  #prometheus.io/scrape: 'true'
  #metrics: '/actuator/prometheus'

podSecurityContext: {}
  # fsGroup: 1000
  # runAsNonRoot: true

securityContext: {}
  # allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: true
  # runAsGroup: 1000
  # runAsNonRoot: true
  # runAsUser: 1000
  # capabilities:
  #   drop:
#   - ALL

service:
  type: ClusterIP
  port: 8080
  # enable monitoring and supervision of service
  annotations: {}
  #  prometheus.io/port: '9000'
  #  prometheus.io/scrape: 'true'

# Configuration of ingress controller
ingress:
  # -- enable ingress controller
  enabled: false
  # -- ingress  annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- hosts configuration    
  hosts:
    - host: ""
      paths: [/] # align with contextPath

# Resource requests and limits
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # -- default resource requests
  requests:
    cpu: 100m
    memory: 128Mi
  # -- default resource limits
  limits:
    cpu: 200m
    memory: 1024Mi

# Horizontal Pod Autoscaler configuration
autoscaling:
  # -- enable autoscaling
  enabled: false
  # -- minimum number of replicas
  minReplicas: 1
  # -- maximum number of replicas
  maxReplicas: 5
  # -- target CPU utilization percentages for pod scaling
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Node affinity, tolerations and nodeSelector
nodeSelector: {}

# -- Pod tolerations
tolerations: []

# -- Pod affinity
affinity: {}

# MongoDB Helm chart configuration
mongo:
  # -- enable mongodb chart
  enabled: true
  image:
    # -- docker image registry
    registry: registry.hub.docker.com
    # -- mongodb docker image repository
    repository: bitnamilegacy/mongodb
  # -- MongoDB deployment
  architecture: standalone
  #  -- use StatefulSet
  useStatefulSet: true
  #  -- additional environment variables for mongodb container
  extraEnvVarsSecret: "" # to define
  # -- override mongodb chart name
  fullnameOverride: catalog-mongo
  # -- init scripts to create app user
  initdbScripts:
    init.js: |
      // app user
      db.getSiblingDB("catalog")
      use catalog;
      var username='mongo_user';
      var password=process.env["MONGO_DB_PWD"];
      var user=db.getUser(username);
      if (user == null) {
        print('create user: ' + username);
        db.createUser({user: 'mongo_user',pwd: password,roles: [ { role: 'readWrite', db: 'catalog' } ]});
      } else {
        print('update user: ' + username);
        db.updateUser(username, {pwd: password});
      }
      print('---- done for ' + username);
      quit(0);
  auth:
    # -- enable or disable mongodb root user
    enabled: false
    # -- mongodb root user password
    rootPassword: "" # to define
    # -- mongodb root user name
    rootUser: mongo_user
  persistence:
    # -- enable persistence for mongodb
    enabled: true
    # -- size of mongodb persistence volume
    size: 4Gi
  hidden:
    # persistence for hidden database
    persistence:
      size: 4Gi
  service:
    # -- override mongodb service name
    nameOverride: catalog-mongo
    ports:
      # -- mongodb service port
      mongodb: 27017

otel:
  # activate Open Telemetry instrumentation
  enabled: false
  sidecar:
    # -- use collector agent sidecar
    enabled: false
    # -- main collector address
    jaeger:
      host: ""
      port: 14250
      # main receiver address
    # -- main receiver address
    otlp:
      host: ""
      port: 4317
  attributes:
    # -- resource attribute to be set on telemetry data
    platform: ""
    # -- resource attribute to be set on telemetry data
    region: ""
    # -- resource attribute to be set on telemetry data
    cluster: ""
    # -- resource attribute to be set on telemetry data
    namespace: ""
    # -- resource attribute to be set on telemetry data
    hostname: ""

# fluentd sidecar for logs forwarding
fluentd:
  # -- enable fluentd sidecar container
  enabled: false
  # -- tag value being set on log events and used by fluentd to route logs
  tag: "" 
  # -- hostname of the fluentd instance this application should send logs to. Defaults to localhost
  host: ""

# Monitoring values
monitoring:
  # -- label for application monitoring
  application: ""
  # -- label for exporter autodetection
  domain: ""
  # -- label to specify product name (chart name by default)
  productName: ""
  # -- label to specify topology
  topology: ""
  # -- label to specify role
  role: ""
  # -- label for environment being deployed
  environment: ""

# -- Context path for the application
contextPath: ""
