{{- if .Values.registryCredentials.create -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: gitlab.om-mock-server-tech-pull-token-{{ .Values.environmentType }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order_capture_mock_server.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "order_capture_mock_server.regcredData" . }}
{{- end }}