{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order_capture_mock_server.fullname" . }}-promtail-config
  labels:
    {{- include "order_capture_mock_server.labels" . | nindent 4 }}
stringData:
  promtail.yaml: |
    {{- tpl .Values.promtail.config.file . | nindent 4 }}
{{- end }}