apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "order_capture_mock_server.fullname" . }}
  labels:
    {{- include "order_capture_mock_server.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/mock-server.yml").AsConfig | nindent 2 }}
