# Kustomization for the entangled-frontend application (dev and prod overlays). Applied via Flux.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- entangled-frontend-dev.yaml
- entangled-frontend-prod.yaml

