apiVersion: v2
appVersion: 1.7.0
description: A Helm chart for [disco-catalog]/[catalog product category] service
home: https://discobole.ow2.io/doc
keywords:
- orange
- discobole
- catalog-product-category
- product-category
name: catalog-product-category
sources:
- https://gitlab.ow2.org/discobole/disco-catalog/catalog-product-category/
type: application
version: 1.7.0
