apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog.fullname" . }}-appconfig
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
data:
   {{- (.Files.Glob "config/application.yaml").AsConfig | nindent 2 }}