# Kustomization de nivel cluster pentru mediul "minirack".
# Aplica flux-system (bootstrap), infrastructura și aplicațiile (bjjbackend, entangled-frontend).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- infrastructure
- bjjbackend
- entangled-frontend
- bjj-dapp-web
- scavangerminephone


