{{- if .Values.registryCredentials.create -}}
kind: Secret #gitleaks:allow
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: gitlab.product-inventory-tech-pull-token-{{ .Values.environmentType }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "productInventory.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "productInventory.regcredData" . }}
{{- end }}