{{- if or .Values.mongo.enabled .Values.mongo.host -}}
apiVersion: v1
kind: Secret #gitleaks:allow
metadata:
  name: product-inventory-mongo-secret-{{ .Values.environmentType }}
  labels:
    {{- include "productInventory.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_DB_PWD: {{ .Values.mongo.auth.rootPassword | b64enc }}
{{- end }} 
