apiVersion: v1
kind: Secret
metadata:
  name: {{ include "productInventory.fullname" . }}-keystore-p12
  labels:
    {{- include "productInventory.labels" . | nindent 4 }}
data:
  keystore-p12: {{ .Values.keyStoreP12}}