{{- if .Values.registryCredentials.create -}}
apiVersion: v1
kind: Secret #gitleaks:allow
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred-{{ template "productInventory.fullname" . }}
  labels:
    {{- include "productInventory.labels" . | nindent 4 }}
data:
  .dockerconfigjson: >-
    {{ template "productInventory.regcredData" . }}
{{- end }}