apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "productInventory.fullname" . }}
  labels:
    {{- include "productInventory.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/productInventory.yml").AsConfig | nindent 2 }}
