{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog.fullname" . }}-promtail-config
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
stringData:
  promtail.yaml: |
    {{- tpl .Values.promtail.config.file . | nindent 4 }}
{{- end }}