apiVersion: v2
appVersion: 1.4.0
description: A Helm chart for [disco-catalog]/[catalog product lifecycle-management]
  service
home: https://discobole.ow2.io/doc
keywords:
- orange
- discobole
- catalog-product-lifecycle-management
- lifecycle-management
name: catalog-product-lifecycle-management
sources:
- https://gitlab.ow2.org/discobole/disco-catalog/catalog-product-lifecycle-management/
type: application
version: 1.4.0
