{{- if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: gateway-keycloak-client-secret
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_CLIENT_SECRET: {{ default "xyz" .Values.keycloak.clientSecret | b64enc }}
{{- end }}
