apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog.fullname" . }}-keystore-p12
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
data:
  keystore-p12: {{ .Values.keyStoreP12}}