apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order_capture_mock_server.fullname" . }}-keystore-p12
  labels:
    {{- include "order_capture_mock_server.labels" . | nindent 4 }}
data:
  keystore-p12: {{ .Values.keyStoreP12}}