{{- if .Values.registryCredentials.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred-{{ template "order_capture_mock_server.fullname" . }}
  labels:
    {{- include "order_capture_mock_server.labels" . | nindent 4 }}
data:
  .dockerconfigjson: >-
    {{ template "order_capture_mock_server.regcredData" . }}
{{- end }}