apiVersion: v1
kind: Service
metadata:
  name: {{ include "order_capture_mock_server.fullname" . }}
  labels:
    {{- include "order_capture_mock_server.labels" . | nindent 4 }}
    name: {{ include "order_capture_mock_server.fullname" . }}
    protocol: tcp
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    {{- include "order_capture_mock_server.selectorLabels" . | nindent 4 }}