apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-catalog-ui.fullname" . }}
  labels:
    {{- include "product-catalog-ui.labels" . | nindent 4 }}
    name: {{ include "product-catalog-ui.fullname" . }}
    protocol: tcp
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # - port: 9000
    #   targetPort: actuator
    #   protocol: TCP
    #   name: actuator
  selector:
    {{- include "product-catalog-ui.selectorLabels" . | nindent 4 }}