{{- if .Values.registryCredentials.create -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: gitlab-order-follow-up-tech-pull-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order_follow_up.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "order_follow_up.regcredData" . }}
{{- end }}