apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "order_follow_up.fullname" . }}-network-policy
  labels:
    {{- include "order_follow_up.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "order_follow_up.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - {}