apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order_follow_up.fullname" . }}-keystore-p12
  labels:
    {{- include "order_follow_up.labels" . | nindent 4 }}
data:
  keystore-p12: {{ .Values.keyStoreP12}}