# Deployment patch for entangled-frontend prod environment to update ConfigMap reference.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-entangled-frontend-web
  namespace: entangled-frontend
spec:
  template:
    spec:
      containers:
        - name: container-entangled-frontend-web
          envFrom:
            - configMapRef:
                name: prod-configmap-entangled-frontend
